theme: jekyll-theme-architect
title: Learn DVCS
description: Fundamentals of Distributed Version Control with git on GitHub
repository: dgilleland/gh-theme-simple-course
show_downloads: false
encoding: utf-8
collections:
  colophon:
    output: true
  jamstack:
    output: true
  chap_ters:
    output: true
